FROM bellsoft/liberica-openjdk-alpine as BuildProject
WORKDIR /app
COPY ./java ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d out ./src/ru/geekBrains/lesson01/sample/Main.java

FROM scratch as OutputFiles
COPY --from=BuildProject /app/out /bin




# FROM bellsoft/liberica-openjdk-alpine:11.0.16
# COPY ./java ./src
# RUN mkdir ./out
# RUN javac -sourcepath ./src -d out src/ru/geekbrains/lesson1/sample/Main.java
# CMD java -classpath ./out ru.geekbrains.lesson1.sample.Main
